### ISSUE TITLE
Link dead ?

### ISSUE THREAD

**Issue by nakyto** [green-code-initiative/creedengo-python#42]
Hello, i find some dead link

**Describe the bug**

In the README.MD

`Configure local SonarQube (security config and quality profile : see [configuration](https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/INSTALL.md#configuration-sonarqube)`

**To Reproduce**

Click on main branche : https://github.com/green-code-initiative/ecoCode-python

it the same for JAVA for docker _all-in-one_

`https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/INSTALL.md`

**Comment by dedece35** [comment]
thank you @nakyto.
correction done on "main" branch.
This correction will be released with next plugin version.
